# -*- coding: utf-8 -*-
"""jenica to-do list model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11k0RSmqWKaIbkNGRiPcEHRFwIHXMgbNj
"""

base code

# Simple To-Do List App

tasks = []   # empty list to store tasks

def show_menu():
    print("\n--- TO DO LIST MENU ---")
    print("1. Add Task")
    print("2. View Tasks")
    print("3. Delete Task")
    print("4. Exit")

def add_task():
    task = input("Enter your task: ")
    tasks.append(task)
    print("Task added!")

def view_tasks():
    if len(tasks) == 0:
        print("No tasks yet!")
    else:
        print("\nYour Tasks:")
        for i, task in enumerate(tasks, 1):
            print(f"{i}. {task}")

def delete_task():
    view_tasks()
    if len(tasks) > 0:
        try:
            num = int(input("Enter task number to delete: "))
            tasks.pop(num - 1)
            print("Task deleted!")
        except:
            print("Invalid number!")

# Main Loop
while True:
    show_menu()
    choice = input("Choose an option (1-4): ")

    if choice == "1":
        add_task()
    elif choice == "2":
        view_tasks()
    elif choice == "3":
        delete_task()
    elif choice == "4":
        print("Goodbye!")
        break
    else:
        print("Invalid option, try again!")

modified code

#!/usr/bin/env python3
"""
Upgraded To-Do List App
Features:
- Add tasks with deadlines
- Save/load tasks to tasks.json (persistent storage)
- View tasks (shows index, task, deadline, status)
- Delete tasks
- Mark tasks as completed
- Search tasks by keyword
- Simple input validation and error handling
- Optional colored output using colorama (if installed)
"""

import json
import os
from datetime import datetime

# Dummy classes for Fore and Style if colorama is not available
class DummyColor:
    def __getattr__(self, name):
        return ""

class DummyStyle:
    def __getattr__(self, name):
        return ""

# Initialize with dummy objects
Fore = DummyColor()
Style = DummyStyle()
COLOR_ENABLED = False

# Try to import colorama for colored terminal output; fallback gracefully if not available
try:
    from colorama import Fore as ColoramaFore, Style as ColoramaStyle, init as colorama_init
    colorama_init(autoreset=True)
    Fore = ColoramaFore  # Overwrite with actual colorama objects
    Style = ColoramaStyle
    COLOR_ENABLED = True
except Exception:
    # If colorama import fails, Fore and Style remain as DummyColor/DummyStyle
    pass # COLOR_ENABLED is already False

DATA_FILE = "tasks.json"
tasks = []  # in-memory list of tasks (each task is a dict)


# ---------- Utility functions ----------
def colored(text, color_obj):
    """Return colored text if colorama is available, otherwise plain text."""
    # The color_obj is now directly used, and if colorama failed, it's a DummyColor object
    return f"{color_obj}{text}{Style.RESET_ALL}"


def save_tasks():
    """Save tasks list to JSON file."""
    try:
        with open(DATA_FILE, "w") as f:
            json.dump(tasks, f, indent=2)
    except Exception as e:
        print(colored(f"Error saving tasks: {e}", Fore.RED))


def load_tasks():
    """Load tasks from JSON file into memory. If file missing, start with empty list."""
    global tasks
    if not os.path.exists(DATA_FILE):
        tasks = []
        return
    try:
        with open(DATA_FILE, "r") as f:
            tasks = json.load(f)
    except Exception:
        tasks = []


def valid_index(idx):
    """Check if idx is a valid 1-based index for tasks list."""
    return 1 <= idx <= len(tasks)


def input_nonempty(prompt):
    """Prompt until user enters a non-empty string."""
    while True:
        val = input(prompt).strip()
        if val:
            return val
        print(colored("Input cannot be empty. Try again.", Fore.YELLOW))


# ---------- Core features ----------
def show_menu():
    print("\n" + "-" * 28)
    print(colored("   SIMPLE TO-DO LIST (UPGRADED)", Fore.CYAN))
    print("-" * 28)
    print("1. Add Task")
    print("2. View Tasks")
    print("3. Delete Task")
    print("4. Mark Task Completed")
    print("5. Search Tasks")
    print("6. Clear All Tasks")
    print("7. Exit")


def add_task():
    task_text = input_nonempty("Enter your task: ")
    deadline = input("Enter deadline (optional, e.g. 2025-12-31 or 'tomorrow'): ").strip()
    # Optionally try to normalize date-like input (not required)
    # We'll just store whatever the user types; you could parse with datetime if you'd like.
    task = {
        "task": task_text,
        "deadline": deadline,
        "done": False,
        "created_at": datetime.now().isoformat()
    }
    tasks.append(task)
    save_tasks()
    print(colored("Task added!", Fore.GREEN))


def view_tasks(show_all=True):
    if len(tasks) == 0:
        print(colored("\nNo tasks yet!", Fore.YELLOW))
        return

    print("\nYour Tasks:")
    for i, t in enumerate(tasks, 1):
        status = colored("✔ Done", Fore.GREEN) if t.get("done") else colored("⏳ Not Done", Fore.MAGENTA)
        deadline = t.get("deadline", "")
        deadline_str = f"(Deadline: {deadline})" if deadline else "(No deadline)"
        # Short created time for display (optional)
        created = t.get("created_at", "")[:19].replace("T", " ") if t.get("created_at") else ""
        print(f"{i}. {t.get('task')} {deadline_str} [{status}]  (Added: {created})")


def delete_task():
    view_tasks()
    if len(tasks) == 0:
        return
    try:
        num = int(input("Enter task number to delete: ").strip())
        if not valid_index(num):
            print(colored("Invalid task number.", Fore.RED))
            return
        removed = tasks.pop(num - 1)
        save_tasks()
        print(colored(f"Removed task: {removed.get('task')}", Fore.GREEN))
    except ValueError:
        print(colored("Please enter a valid number.", Fore.YELLOW))


def mark_done():
    view_tasks()
    if len(tasks) == 0:
        return
    try:
        num = int(input("Enter task number to mark as done: ").strip())
        if not valid_index(num):
            print(colored("Invalid task number.", Fore.RED))
            return
        tasks[num - 1]["done"] = True
        save_tasks()
        print(colored("Task marked as completed!", Fore.GREEN))
    except ValueError:
        print(colored("Please enter a valid number.", Fore.YELLOW))


def search_task():
    keyword = input_nonempty("Enter keyword to search: ").lower()
    found = []
    for i, t in enumerate(tasks, 1):
        if keyword in t.get("task", "").lower() or keyword in (t.get("deadline") or "").lower():
            found.append((i, t))
    if not found:
        print(colored("No matching tasks found.", Fore.YELLOW))
        return
    print("\nSearch Results:")
    for i, t in found:
        status = "Done" if t.get("done") else "Not Done"
        print(f"{i}. {t.get('task')} (Deadline: {t.get('deadline')}) [{status}]")


def clear_all_tasks():
    confirm = input("Are you sure you want to CLEAR ALL tasks? This cannot be undone (y/n): ").strip().lower()
    if confirm == "y":
        tasks.clear()
        save_tasks()
        print(colored("All tasks cleared.", Fore.GREEN))
    else:
        print("Clear cancelled.")


# ---------- Main Program ----------
def main():
    load_tasks()
    while True:
        show_menu()
        choice = input("Choose an option (1-7): ").strip()
        if choice == "1":
            add_task()
        elif choice == "2":
            view_tasks()
        elif choice == "3":
            delete_task()
        elif choice == "4":
            mark_done()
        elif choice == "5":
            search_task()
        elif choice == "6":
            clear_all_tasks()
        elif choice == "7":
            print(colored("Goodbye! Your tasks are saved in tasks.json", Fore.CYAN))
            break
        else:
            print(colored("Invalid option, try again.", Fore.YELLOW))


if __name__ == "__main__":
    main()